{% set name = "cylc-ui" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cylc/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}-dist.zip
  sha256: 0c60829e76ab7820a6ef3c0394b05ea3390648234a9e5da97470892bc99bb897
  folder: cylc-ui

build:
  number: 1
  # Cylc Flow is Linux only. Cylc UI could be built on Windows/Mac/etc, but we are assuming the whole build env to be Linux
  skip: True  # [not linux]

test:
  commands:
    - echo "OK"

about:
  home: https://github.com/cylc/cylc-ui
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Cylc Web UI'

  description: |
    Cylc Web UI.
  doc_url: https://github.com/cylc/cylc-ui
  dev_url: https://github.com/cylc/cylc-ui

extra:
  recipe-maintainers:
    - hjoliver
    - kinow
    - oliver-sanders
