{% set name = "cylc-ui" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cylc/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}-dist.zip
  sha256: 64c1ca60ea2d54e5109e792ebc8a7b773d4205649a92f0c4f5322be5d919fe8f
  folder: cylc-ui

build:
  number: 0
  # Cylc Flow is Linux only. Cylc UI could be built on Windows/Mac/etc, but we are assuming the whole build env to be Linux
  skip: true  # [not linux]

test:
  commands:
    - echo "OK"

about:
  home: https://github.com/cylc/cylc-ui
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Cylc Web UI

  description: |
    Cylc UI is bundled with the cylc-uiserver package.
    You should not need to install this package separately.

  doc_url: https://github.com/cylc/cylc-ui
  dev_url: https://github.com/cylc/cylc-ui

extra:
  recipe-maintainers:
    - hjoliver
    - oliver-sanders
