{% set name = "cylc-ui" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cylc/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}-dist.zip
  sha256: 72f15acb4d5b779999712c9b59aec69653f3e20264bc6de010d243d5ef1b2cb1
  folder: cylc-ui

build:
  number: 0
  # Cylc Flow is Linux only. Cylc UI could be built on Windows/Mac/etc, but we are assuming the whole build env to be Linux
  skip: true  # [not linux]

test:
  commands:
    - echo "OK"

about:
  home: https://github.com/cylc/cylc-ui
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Cylc Web UI

  description: |
    Cylc UI is bundled with the cylc-uiserver package.
    You should not need to install this package separately.

  doc_url: https://github.com/cylc/cylc-ui
  dev_url: https://github.com/cylc/cylc-ui

extra:
  recipe-maintainers:
    - hjoliver
    - oliver-sanders
